### ISSUE TITLE
Error while loading pickle (Can't get attribute 'SignificanceRow')

### ISSUE THREAD

**Issue by rahatzamancse** [enoriega/frailty_graph_viz#19]
When I try to run the backend using `python -m backend.start --graph-file data/graph_temp.pickle`. I get the error like the below:

```text
Loading data ...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "frailty_graph_viz/backend/start.py", line 10, in <module>
    from .viz_api import api_router as viz_api_router
  File "frailty_graph_viz/backend/viz_api.py", line 205, in <module>
    def interaction(source, destination, bidirectional: bool, graph: MultiDiGraph = get_graph(),
  File "frailty_graph_viz/backend/dependencies.py", line 108, in get_graph
    graph, _ = read_graph_and_significance()
  File "frailty_graph_viz/backend/dependencies.py", line 89, in read_graph_and_significance
    data = pickle.load(f)
```

[This SO](https://stackoverflow.com/questions/27732354/unable-to-load-files-using-pickle-and-multiple-modules) might help to resolve this issue.

I think this is related to commit 0e90e30004fb7796996d57a33332a2cdea27f076, where you moved the class `SignificanceRow` to network.py, but the stored pickle file is still looking for the class in the old place. The solution is to rebuild the pickle file in the current context again.

Later down the road, I believe we should get rid of pickles as the medium of data and switch to something more robust like csv/json or more specialized for graph like dot files.

**Comment by enoriega** [comment]
@rahatzamancse I rebuilt the pickle files after the update. They're in box. Please download them and try again.

W.r.t. deprecating the pickle file: I agree. I like the idea of using dot files. I also think we should enable using Neo4J or a graph database as a database because it will be likely that the data won't fit in memory once we annotate all of pubmed

**Comment by enoriega** [comment]
I can't replicate this on the backend branch. I think it has to do with the removal of the relative imports.
If I open a python shell and load the pickle files from it, they work.
I can't start uvicorn either, but with a different error message. I believe that `PYTHONPATH` is different in our environments and that messing with the relative imports is causing discrepancies. Let's try to revert the imports back and figure out how to make it work that way

**Comment by enoriega** [comment]
This was an issue with the relative imports being removed. So it is safe to close it.
